# Generated by Django 3.2 on 2021-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img')),
            ],
            options={
                'verbose_name': 'Dinossauro',
                'verbose_name_plural': 'Dinossauros',
                'ordering': ('name',),
            },
        ),
    ]
